sudo: required
services:
  - docker

before_install:
  - docker build -t karanjain88/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true karanjain88/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-970124477043"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KET"