version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:  
      - checkout
      - run:
          name: Build the Dockerfile
          command: |
            echo $DOCKER_USERNAME | docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run:
          name: Run the Dockerfile
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker run -e CI=true cygnetops/react-test npm test
