version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:  
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build the Dockerfile
          command: |
            docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run:
          name: Run the Dockerfile
          command: |
            docker login -u karan2fady -p Svaley@321
            docker run -e CI=true cygnetops/react-test npm test