version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:  
      - checkout
      - run:
          name: Build the Dockerfile
          command: |
            echo $DOCKER_USERNAME | echo $DOCKER_PASSWORD
