name: docker-react CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker-react repo
        uses: actions/checkout@v4
      - name: Docker build and run using Dockerfile.dev file
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker run -e CI=true cygnetops/react-test npm test