name: docker-react CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker-react repo
        uses: actions/checkout@v4
      - name: Check if all the tests pass using Dockerfile.dev file
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f Dockerfile.dev .
          docker run -e CI=true cygnetops/react-test npm test
          
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docker-react repo
        uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: frontend
          environment_name: Frontend-env-3
          existing_bucket_name: elasticbeanstalk-us-east-1-677276121529
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip